In [2]:
import numpy as np

In [ ]:
# 1. Prime Clusters - Given a 2D NumPy array, write a function to find the rows where at least one value is a prime number.

arr = np.array([[2, 3, 5], [4, 6, 8], [11, 13, 17], [7, 10, 13]])

def isPrime(num):
    for i in range (2, int(np.sqrt(num))+1):
        if num <= 1:
            return False 
        if (num % i) == 0:
            return False
        else:
            return True

result = []
for row in arr:
    if any(isPrime(elem) for elem in row):
        result.append(row)
np.array(result)

array([[ 2,  3,  5],
       [11, 13, 17],
       [ 7, 10, 13]])

In [ ]:
# 2. Let's play Checkers!
# 2.1 - Start by writing a function that creates a 8x8 square matrix with only zeros.

def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    return board
checkerboard()

array([[0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 2.2 - For only the odd rows, make an alternating pattern of ones and zeroes.

def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2,::2]=1
    return board
checkerboard()

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 0, 0, 0, 0, 0, 0, 0]])

In [ ]:
# 2.3 - Finish the checkerboard with the even rows.

def checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[::2,::2]=1
    board[1::2,1::2]=1
    return board
checkerboard()

array([[1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1]])

In [ ]:
# 2.4 - Re-write your function such that the checkerboard begins with a 0 instead.

def reverse_checkerboard():
    board = np.zeros((8, 8), dtype=int)
    board[1::2,::2]=1
    board[::2,1::2]=1
    return board
reverse_checkerboard()

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [27]:
# 3. The Expanding Universe - Write a function that takes in a string and a number, and returns the string with the specified number of spaces inserted between each letter, simulating the expansion of space!

universe = np.array(['galaxy', 'clusters'])
def expansion(universe, spaces):
    def add_spaces(word):
        gap = " " * spaces
        return gap.join(word)
    return np.array([add_spaces(word) for word in universe])

print(list(expansion(universe, 1)))
print(list(expansion(universe, 2)))

['g a l a x y', 'c l u s t e r s']
['g  a  l  a  x  y', 'c  l  u  s  t  e  r  s']


In [ ]:
# 4. Second Dimmest Star - Write a function that takes a 2D NumPy array and returns an array containing only the second-smallest value in each column.

np.random.seed(123)
stars = np.random.randint(500, 2000, (5, 5))
print(stars) # displays the random 2D array

def secondDimmest(stars):
    sorted = np.sort(stars, axis = 0) # axis = 0 sorts by column 
    return sorted[1] # slices array to only return second row (index 1)

secondDimmest(stars)

[[1889 1906 1846 1622 1541]
 [ 606 1647 1738  596  613]
 [1138  547  573 1442  724]
 [ 611 1933 1863 1346 1777]
 [ 920 1108 1732 1592  951]]


array([ 611, 1108, 1732, 1346,  724])